import chalk from 'chalk';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ext = (ts) => ts ? 'ts' : 'js';

export async function createProject(config) {
  const { name, database, auth, cache, type, optimizations, typescript = false, docker = false } = config;
  const projectPath = path.join(process.cwd(), name);

  if (await fs.pathExists(projectPath)) {
    console.log(chalk.red(`  ✖ Directory "${name}" already exists.`));
    console.log('');
    process.exit(1);
  }

  if (typescript) {
    console.log(chalk.blue(`  🔷 TypeScript mode enabled`));
  }
  console.log(chalk.gray(`  Creating project: ${chalk.white(name)}...`));

  const dirs = [
    'src/app',
    'src/modules/example',
    'src/core/middleware',
    'src/core/database',
    'src/core/utils',
    'src/config',
  ];

  for (const dir of dirs) {
    await fs.ensureDir(path.join(projectPath, dir));
  }

  await writePackageJson(projectPath, name, database, auth, cache, typescript);
  await writeMainFile(projectPath, type, typescript);
  await writeServerFile(projectPath, typescript);
  await writeRoutesFile(projectPath, auth, typescript);
  await writeEnvConfig(projectPath, database, typescript);
  await writeExampleModule(projectPath, typescript);
  await writeMiddleware(projectPath, auth, typescript);
  await writeDatabaseLayer(projectPath, database, typescript);
  await writeUtils(projectPath, typescript);
  await writeEnvFile(projectPath, database);
  await writeReadme(projectPath, name, database, auth, cache, type, typescript);
  await writeGitignore(projectPath, typescript);

  if (typescript) {
    await writeTsConfig(projectPath);
  }

  // Docker files
  if (docker) {
    await writeDockerFiles(projectPath, name, database, typescript);
  }

  if (auth) await writeAuthPlugin(projectPath, typescript);
  if (database === 'mysql') await writeMysqlPlugin(projectPath);
  if (database === 'sqlite') await writeSqlitePlugin(projectPath);
  if (cache) await writeCachePlugin(projectPath, typescript);
  if (optimizations) await writeLoggerPlugin(projectPath, typescript);

  console.log(chalk.green(`  ✔ Project created: ${chalk.bold(name)}`));
  console.log('');
  console.log(chalk.gray('  Next steps:'));
  console.log(chalk.cyan(`    cd ${name}`));
  console.log(chalk.cyan('    npm install'));
  if (docker) {
    console.log(chalk.cyan('    docker compose up --build'));
  } else if (typescript) {
    console.log(chalk.cyan('    npm run dev'));
  } else {
    console.log(chalk.cyan('    nexorix run'));
  }
  console.log('');
}

async function writePackageJson(projectPath, name, database, auth, cache, typescript = false) {
  const deps = {};
  const devDeps = {};

  if (database === 'mysql') deps['mysql2'] = '^3.9.7';
  if (database === 'sqlite') deps['better-sqlite3'] = '^9.4.3';
  if (auth) deps['jsonwebtoken'] = '^9.0.2';
  if (cache) deps['node-cache'] = '^5.1.2';

  const scripts = typescript
    ? {
        start: 'node dist/main.js',
        dev: 'tsx watch src/main.ts',
        build: 'tsc',
        'build:check': 'tsc --noEmit',
      }
    : {
        start: 'node src/main.js',
        dev: 'node --watch src/main.js',
      };

  if (typescript) {
    devDeps['typescript'] = '^5.4.5';
    devDeps['tsx'] = '^4.11.0';
    devDeps['@types/node'] = '^20.12.7';
    if (auth) devDeps['@types/jsonwebtoken'] = '^9.0.6';
    if (database === 'sqlite') devDeps['@types/better-sqlite3'] = '^7.6.10';
  }

  const pkg = {
    name,
    version: '1.0.0',
    description: `${name} — generated by Nexorix`,
    ...(typescript ? {} : { type: 'module' }),
    scripts,
    ...(Object.keys(deps).length > 0 ? { dependencies: deps } : {}),
    ...(Object.keys(devDeps).length > 0 ? { devDependencies: devDeps } : {}),
  };

  await fs.writeJson(path.join(projectPath, 'package.json'), pkg, { spaces: 2 });
}

async function writeMainFile(projectPath, type, typescript = false) {
  const e = ext(typescript);
  const importExt = typescript ? '' : '.js';

  const content = typescript
    ? `import { createServer } from './app/server${importExt}';
import { config } from './config/env${importExt}';

const PORT: number = config.port || 3000;

const server = createServer();

server.listen(PORT, () => {
  console.log(\`[nexorix] Server running on http://localhost:\${PORT}\`);
  console.log(\`[nexorix] Environment: \${config.env}\`);
  ${type === 'microservice' ? "console.log('[nexorix] Mode: Microservice');" : "console.log('[nexorix] Mode: API REST');"}
});

server.on('error', (err: Error) => {
  console.error('[nexorix] Server error:', err.message);
  process.exit(1);
});
`
    : `import { createServer } from './app/server.js';
import { config } from './config/env.js';

const PORT = config.port || 3000;

const server = createServer();

server.listen(PORT, () => {
  console.log(\`[nexorix] Server running on http://localhost:\${PORT}\`);
  console.log(\`[nexorix] Environment: \${config.env}\`);
  ${type === 'microservice' ? "console.log('[nexorix] Mode: Microservice');" : "console.log('[nexorix] Mode: API REST');"}
});

server.on('error', (err) => {
  console.error('[nexorix] Server error:', err.message);
  process.exit(1);
});
`;

  await fs.writeFile(path.join(projectPath, 'src', `main.${e}`), content);
}

async function writeServerFile(projectPath, typescript = false) {
  const e = ext(typescript);

  const content = typescript
    ? `import http from 'http';
import { router } from './routes';

export function createServer(): http.Server {
  return http.createServer((req: http.IncomingMessage, res: http.ServerResponse) => {
    // CORS headers
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

    if (req.method === 'OPTIONS') {
      res.writeHead(204);
      res.end();
      return;
    }

    // Body parser
    let body = '';
    req.on('data', (chunk: Buffer) => { body += chunk.toString(); });
    req.on('end', () => {
      try {
        (req as any).body = body ? JSON.parse(body) : {};
      } catch {
        (req as any).body = {};
      }
      router(req, res);
    });
  });
}

export function sendJson(res: http.ServerResponse, statusCode: number, data: unknown): void {
  res.writeHead(statusCode, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(data));
}
`
    : `import http from 'http';
import { router } from './routes.js';

export function createServer() {
  return http.createServer((req, res) => {
    // CORS headers
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

    if (req.method === 'OPTIONS') {
      res.writeHead(204);
      res.end();
      return;
    }

    // Body parser
    let body = '';
    req.on('data', (chunk) => { body += chunk.toString(); });
    req.on('end', () => {
      try {
        req.body = body ? JSON.parse(body) : {};
      } catch {
        req.body = {};
      }
      router(req, res);
    });
  });
}

export function sendJson(res, statusCode, data) {
  res.writeHead(statusCode, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(data));
}
`;

  await fs.writeFile(path.join(projectPath, 'src', 'app', `server.${e}`), content);
}

async function writeRoutesFile(projectPath, auth, typescript = false) {
  const e = ext(typescript);

  const content = typescript
    ? `import http from 'http';
import { sendJson } from './server';
import { exampleController } from '../modules/example/example.controller';
${auth ? "import { authMiddleware } from '../core/middleware/auth.middleware';" : ''}

type RouteHandler = (req: http.IncomingMessage, res: http.ServerResponse) => void;

const routes: Record<string, RouteHandler> = {
  'GET /': (req, res) => sendJson(res, 200, {
    status: 'ok',
    message: 'Nexorix API is running',
    version: '1.0.0',
  }),
  'GET /health': (req, res) => sendJson(res, 200, {
    status: 'healthy',
    uptime: process.uptime(),
    timestamp: new Date().toISOString(),
  }),
  'GET /api/examples': exampleController.list,
  'GET /api/examples/:id': exampleController.findById,
  'POST /api/examples': exampleController.create,
};

export function router(req: http.IncomingMessage, res: http.ServerResponse): void {
  const url = (req.url || '/').split('?')[0];
  const method = req.method || 'GET';

  for (const [pattern, handler] of Object.entries(routes)) {
    const [routeMethod, routePath] = pattern.split(' ');
    if (routeMethod !== method) continue;

    const match = matchRoute(routePath, url);
    if (match) {
      (req as any).params = match;
      ${auth ? `
      const protectedPaths = ['/api/examples'];
      const isProtected = protectedPaths.some(p => url.startsWith(p));
      if (isProtected && method !== 'GET') {
        const authResult = authMiddleware(req, res);
        if (!authResult) return;
      }
      ` : ''}
      return handler(req, res);
    }
  }

  sendJson(res, 404, { error: 'Route not found', path: url, method });
}

function matchRoute(pattern: string, url: string): Record<string, string> | null {
  const patternParts = pattern.split('/');
  const urlParts = url.split('/');

  if (patternParts.length !== urlParts.length) return null;

  const params: Record<string, string> = {};
  for (let i = 0; i < patternParts.length; i++) {
    if (patternParts[i].startsWith(':')) {
      params[patternParts[i].slice(1)] = urlParts[i];
    } else if (patternParts[i] !== urlParts[i]) {
      return null;
    }
  }
  return params;
}
`
    : `import { sendJson } from './server.js';
import { exampleController } from '../modules/example/example.controller.js';
${auth ? "import { authMiddleware } from '../core/middleware/auth.middleware.js';" : ''}

const routes = {
  'GET /': (req, res) => sendJson(res, 200, {
    status: 'ok',
    message: 'Nexorix API is running',
    version: '1.0.0',
  }),
  'GET /health': (req, res) => sendJson(res, 200, {
    status: 'healthy',
    uptime: process.uptime(),
    timestamp: new Date().toISOString(),
  }),
  'GET /api/examples': exampleController.list,
  'GET /api/examples/:id': exampleController.findById,
  'POST /api/examples': exampleController.create,
};

export function router(req, res) {
  const url = req.url.split('?')[0];
  const method = req.method;

  for (const [pattern, handler] of Object.entries(routes)) {
    const [routeMethod, routePath] = pattern.split(' ');
    if (routeMethod !== method) continue;

    const match = matchRoute(routePath, url);
    if (match) {
      req.params = match;
      ${auth ? `
      const protectedPaths = ['/api/examples'];
      const isProtected = protectedPaths.some(p => url.startsWith(p));
      if (isProtected && method !== 'GET') {
        const authResult = authMiddleware(req, res);
        if (!authResult) return;
      }
      ` : ''}
      return handler(req, res);
    }
  }

  sendJson(res, 404, { error: 'Route not found', path: url, method });
}

function matchRoute(pattern, url) {
  const patternParts = pattern.split('/');
  const urlParts = url.split('/');

  if (patternParts.length !== urlParts.length) return null;

  const params = {};
  for (let i = 0; i < patternParts.length; i++) {
    if (patternParts[i].startsWith(':')) {
      params[patternParts[i].slice(1)] = urlParts[i];
    } else if (patternParts[i] !== urlParts[i]) {
      return null;
    }
  }
  return params;
}
`;

  await fs.writeFile(path.join(projectPath, 'src', 'app', `routes.${e}`), content);
}

async function writeEnvConfig(projectPath, database, typescript = false) {
  const e = ext(typescript);

  const tsInterface = typescript ? `
interface DbConfig {
  host: string;
  port: number;
  user: string;
  password: string;
  database: string;
}

interface Config {
  env: string;
  port: number;
  ${database === 'mysql' ? 'db: DbConfig;' : ''}
  ${database === 'sqlite' ? 'db: { path: string };' : ''}
  jwt: {
    secret: string;
    expiresIn: string;
  };
}
` : '';

  const content = `import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
${tsInterface}
function loadEnv(): void {
  const envPath = join(process.cwd(), '.env');
  if (existsSync(envPath)) {
    const lines = readFileSync(envPath, 'utf-8').split('\\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const [key, ...rest] = trimmed.split('=');
      if (key && !process.env[key]) {
        process.env[key] = rest.join('=').trim();
      }
    }
  }
}

loadEnv();

export const config${typescript ? ': Config' : ''} = {
  env: process.env.NODE_ENV || 'development',
  port: parseInt(process.env.PORT || '3000', 10),
  ${database === 'mysql' ? `
  db: {
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '3306', 10),
    user: process.env.DB_USER || 'root',
    password: process.env.DB_PASSWORD || '',
    database: process.env.DB_NAME || 'nexorix_db',
  },` : ''}
  ${database === 'sqlite' ? `
  db: {
    path: process.env.DB_PATH || './data/database.sqlite',
  },` : ''}
  jwt: {
    secret: process.env.JWT_SECRET || 'nexorix-secret-change-in-production',
    expiresIn: process.env.JWT_EXPIRES_IN || '7d',
  },
};
`;
  await fs.writeFile(path.join(projectPath, 'src', 'config', `env.${e}`), content);
}

async function writeExampleModule(projectPath, typescript = false) {
  const e = ext(typescript);
  const modulePath = path.join(projectPath, 'src', 'modules', 'example');
  const imp = typescript ? '' : '.js';

  // Controller
  const controller = typescript
    ? `import http from 'http';
import { sendJson } from '../../app/server';
import { ExampleService } from './example.service';

const service = new ExampleService();

export const exampleController = {
  async list(req: http.IncomingMessage, res: http.ServerResponse): Promise<void> {
    try {
      const data = await service.findAll();
      sendJson(res, 200, { data, total: data.length });
    } catch (err) {
      sendJson(res, 500, { error: (err as Error).message });
    }
  },

  async findById(req: http.IncomingMessage, res: http.ServerResponse): Promise<void> {
    try {
      const id = (req as any).params?.id;
      const item = await service.findById(id);
      if (!item) return sendJson(res, 404, { error: 'Not found' });
      sendJson(res, 200, { data: item });
    } catch (err) {
      sendJson(res, 500, { error: (err as Error).message });
    }
  },

  async create(req: http.IncomingMessage, res: http.ServerResponse): Promise<void> {
    try {
      const item = await service.create((req as any).body);
      sendJson(res, 201, { data: item, message: 'Created successfully' });
    } catch (err) {
      sendJson(res, 400, { error: (err as Error).message });
    }
  },
};
`
    : `import { sendJson } from '../../app/server.js';
import { ExampleService } from './example.service.js';

const service = new ExampleService();

export const exampleController = {
  async list(req, res) {
    try {
      const data = await service.findAll();
      sendJson(res, 200, { data, total: data.length });
    } catch (err) {
      sendJson(res, 500, { error: err.message });
    }
  },

  async findById(req, res) {
    try {
      const item = await service.findById(req.params.id);
      if (!item) return sendJson(res, 404, { error: 'Not found' });
      sendJson(res, 200, { data: item });
    } catch (err) {
      sendJson(res, 500, { error: err.message });
    }
  },

  async create(req, res) {
    try {
      const item = await service.create(req.body);
      sendJson(res, 201, { data: item, message: 'Created successfully' });
    } catch (err) {
      sendJson(res, 400, { error: err.message });
    }
  },
};
`;

  // Service
  const service = typescript
    ? `import { ExampleRepository } from './example.repository';

export interface ExampleItem {
  id: string;
  [key: string]: unknown;
}

export class ExampleService {
  private repository: ExampleRepository;

  constructor() {
    this.repository = new ExampleRepository();
  }

  async findAll(): Promise<ExampleItem[]> {
    return this.repository.findAll();
  }

  async findById(id: string): Promise<ExampleItem | null> {
    if (!id) throw new Error('ID is required');
    return this.repository.findById(id);
  }

  async create(data: Record<string, unknown>): Promise<ExampleItem> {
    if (!data || Object.keys(data).length === 0) {
      throw new Error('Data is required');
    }
    return this.repository.create(data);
  }
}
`
    : `import { ExampleRepository } from './example.repository.js';

export class ExampleService {
  constructor() {
    this.repository = new ExampleRepository();
  }

  async findAll() {
    return this.repository.findAll();
  }

  async findById(id) {
    if (!id) throw new Error('ID is required');
    return this.repository.findById(id);
  }

  async create(data) {
    if (!data || Object.keys(data).length === 0) {
      throw new Error('Data is required');
    }
    return this.repository.create(data);
  }
}
`;

  // Repository
  const repository = typescript
    ? `import { ExampleItem } from './example.service';

// In-memory repository — replace with real DB layer
const store: ExampleItem[] = [
  { id: '1', name: 'Example Item 1', createdAt: new Date().toISOString() },
  { id: '2', name: 'Example Item 2', createdAt: new Date().toISOString() },
];

let nextId = 3;

export class ExampleRepository {
  async findAll(): Promise<ExampleItem[]> {
    return [...store];
  }

  async findById(id: string): Promise<ExampleItem | null> {
    return store.find((item) => item.id === String(id)) || null;
  }

  async create(data: Record<string, unknown>): Promise<ExampleItem> {
    const item: ExampleItem = {
      id: String(nextId++),
      ...data,
      createdAt: new Date().toISOString(),
    };
    store.push(item);
    return item;
  }
}
`
    : `// In-memory repository — replace with real DB layer
const store = [
  { id: '1', name: 'Example Item 1', createdAt: new Date().toISOString() },
  { id: '2', name: 'Example Item 2', createdAt: new Date().toISOString() },
];

let nextId = 3;

export class ExampleRepository {
  async findAll() {
    return [...store];
  }

  async findById(id) {
    return store.find((item) => item.id === String(id)) || null;
  }

  async create(data) {
    const item = {
      id: String(nextId++),
      ...data,
      createdAt: new Date().toISOString(),
    };
    store.push(item);
    return item;
  }
}
`;

  await fs.writeFile(path.join(modulePath, `example.controller.${e}`), controller);
  await fs.writeFile(path.join(modulePath, `example.service.${e}`), service);
  await fs.writeFile(path.join(modulePath, `example.repository.${e}`), repository);
}

async function writeMiddleware(projectPath, auth, typescript = false) {
  const e = ext(typescript);
  const middlewarePath = path.join(projectPath, 'src', 'core', 'middleware');

  const authMiddleware = typescript
    ? `import http from 'http';

export function authMiddleware(req: http.IncomingMessage, res: http.ServerResponse): boolean {
  const authHeader = req.headers['authorization'];

  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    res.writeHead(401, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Unauthorized — missing token' }));
    return false;
  }

  const token = authHeader.split(' ')[1];

  try {
    if (!token || token.length < 10) throw new Error('Invalid token');
    const parts = token.split('.');
    if (parts.length === 3) {
      const payload = JSON.parse(Buffer.from(parts[1], 'base64url').toString());
      if (payload.exp && payload.exp < Math.floor(Date.now() / 1000)) {
        throw new Error('Token expired');
      }
      (req as any).user = payload;
    }
    return true;
  } catch (err) {
    res.writeHead(401, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: \`Unauthorized — \${(err as Error).message}\` }));
    return false;
  }
}
`
    : `import { config } from '../../config/env.js';

export function authMiddleware(req, res) {
  const authHeader = req.headers['authorization'];

  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    res.writeHead(401, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Unauthorized — missing token' }));
    return false;
  }

  const token = authHeader.split(' ')[1];

  try {
    if (!token || token.length < 10) throw new Error('Invalid token');
    const parts = token.split('.');
    if (parts.length === 3) {
      const payload = JSON.parse(Buffer.from(parts[1], 'base64url').toString());
      if (payload.exp && payload.exp < Math.floor(Date.now() / 1000)) {
        throw new Error('Token expired');
      }
      req.user = payload;
    }
    return true;
  } catch (err) {
    res.writeHead(401, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: \`Unauthorized — \${err.message}\` }));
    return false;
  }
}
`;

  const errorMiddleware = typescript
    ? `import http from 'http';

export function errorHandler(err: Error & { statusCode?: number }, req: http.IncomingMessage, res: http.ServerResponse): void {
  const statusCode = err.statusCode || 500;
  const message = err.message || 'Internal Server Error';

  console.error(\`[error] \${req.method} \${req.url} — \${message}\`);

  res.writeHead(statusCode, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({
    error: message,
    path: req.url,
    timestamp: new Date().toISOString(),
  }));
}
`
    : `export function errorHandler(err, req, res) {
  const statusCode = err.statusCode || 500;
  const message = err.message || 'Internal Server Error';

  console.error(\`[error] \${req.method} \${req.url} — \${message}\`);

  res.writeHead(statusCode, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({
    error: message,
    path: req.url,
    timestamp: new Date().toISOString(),
  }));
}
`;

  await fs.writeFile(path.join(middlewarePath, `auth.middleware.${e}`), authMiddleware);
  await fs.writeFile(path.join(middlewarePath, `error.middleware.${e}`), errorMiddleware);
}

async function writeDatabaseLayer(projectPath, database, typescript = false) {
  const e = ext(typescript);
  const dbPath = path.join(projectPath, 'src', 'core', 'database');

  if (database === 'mysql') {
    const content = typescript
      ? `import { config } from '../../config/env';
// Requires: npm install mysql2 && npm install -D @types/mysql2
import mysql, { Pool, PoolConnection } from 'mysql2/promise';

let pool: Pool | null = null;

export async function getPool(): Promise<Pool> {
  if (!pool) {
    pool = mysql.createPool({
      host: config.db!.host,
      port: (config.db as any).port,
      user: config.db!.user,
      password: config.db!.password,
      database: config.db!.database,
      waitForConnections: true,
      connectionLimit: 10,
      queueLimit: 0,
    });
    console.log('[database] MySQL pool created');
  }
  return pool;
}

export async function query<T = unknown>(sql: string, params: unknown[] = []): Promise<T[]> {
  const p = await getPool();
  const [rows] = await p.execute(sql, params);
  return rows as T[];
}

export async function transaction<T>(fn: (conn: PoolConnection) => Promise<T>): Promise<T> {
  const p = await getPool();
  const conn = await p.getConnection();
  await conn.beginTransaction();
  try {
    const result = await fn(conn);
    await conn.commit();
    return result;
  } catch (err) {
    await conn.rollback();
    throw err;
  } finally {
    conn.release();
  }
}
`
      : `import { config } from '../../config/env.js';
// Requires: npm install mysql2
import mysql from 'mysql2/promise';

let pool = null;

export async function getPool() {
  if (!pool) {
    pool = mysql.createPool({
      host: config.db.host,
      port: config.db.port,
      user: config.db.user,
      password: config.db.password,
      database: config.db.database,
      waitForConnections: true,
      connectionLimit: 10,
      queueLimit: 0,
    });
    console.log('[database] MySQL pool created');
  }
  return pool;
}

export async function query(sql, params = []) {
  const pool = await getPool();
  const [rows] = await pool.execute(sql, params);
  return rows;
}
`;
    await fs.writeFile(path.join(dbPath, `connection.${e}`), content);

  } else if (database === 'sqlite') {
    const content = typescript
      ? `import { config } from '../../config/env';
import { existsSync, mkdirSync } from 'fs';
import { dirname } from 'path';
// Requires: npm install better-sqlite3 && npm install -D @types/better-sqlite3
import Database, { Database as DB } from 'better-sqlite3';

let db: DB | null = null;

export function getDb(): DB {
  if (!db) {
    const dbPath = (config.db as any).path as string;
    const dir = dirname(dbPath);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    db = new Database(dbPath);
    db.pragma('journal_mode = WAL');
    console.log('[database] SQLite connected:', dbPath);
  }
  return db;
}

export function query<T = unknown>(sql: string, params: unknown[] = []): T[] {
  const database = getDb();
  return database.prepare(sql).all(params) as T[];
}
`
      : `import { config } from '../../config/env.js';
import { existsSync, mkdirSync } from 'fs';
import { dirname } from 'path';
// Requires: npm install better-sqlite3
import Database from 'better-sqlite3';

let db = null;

export function getDb() {
  if (!db) {
    const dir = dirname(config.db.path);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    db = new Database(config.db.path);
    db.pragma('journal_mode = WAL');
    console.log('[database] SQLite connected:', config.db.path);
  }
  return db;
}

export function query(sql, params = []) {
  const db = getDb();
  return db.prepare(sql).all(params);
}
`;
    await fs.writeFile(path.join(dbPath, `connection.${e}`), content);

  } else {
    const content = typescript
      ? `// No database configured.
// Run: nexorix add mysql  or  nexorix add sqlite

export function getDb(): never {
  throw new Error('No database configured. Run: nexorix add mysql');
}
`
      : `// No database configured.
// Run: nexorix add mysql  or  nexorix add sqlite

export function getDb() {
  throw new Error('No database configured. Run: nexorix add mysql');
}
`;
    await fs.writeFile(path.join(dbPath, `connection.${e}`), content);
  }
}

async function writeUtils(projectPath, typescript = false) {
  const e = ext(typescript);
  const utilsPath = path.join(projectPath, 'src', 'core', 'utils');

  const content = typescript
    ? `/**
 * Nexorix Core Utilities
 */

export interface PaginationResult<T> {
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    pages: number;
  };
}

export function paginate<T>(array: T[], page = 1, limit = 10): PaginationResult<T> {
  const offset = (page - 1) * limit;
  return {
    data: array.slice(offset, offset + limit),
    pagination: {
      page,
      limit,
      total: array.length,
      pages: Math.ceil(array.length / limit),
    },
  };
}

export function pick<T extends object, K extends keyof T>(obj: T, keys: K[]): Pick<T, K> {
  return keys.reduce((acc, key) => {
    if (key in obj) acc[key] = obj[key];
    return acc;
  }, {} as Pick<T, K>);
}

export function omit<T extends object, K extends keyof T>(obj: T, keys: K[]): Omit<T, K> {
  return Object.fromEntries(
    Object.entries(obj).filter(([k]) => !keys.includes(k as K))
  ) as Omit<T, K>;
}

export function slugify(str: string): string {
  return str
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2);
}
`
    : `/**
 * Nexorix Core Utilities
 */

export function paginate(array, page = 1, limit = 10) {
  const offset = (page - 1) * limit;
  return {
    data: array.slice(offset, offset + limit),
    pagination: {
      page,
      limit,
      total: array.length,
      pages: Math.ceil(array.length / limit),
    },
  };
}

export function pick(obj, keys) {
  return keys.reduce((acc, key) => {
    if (key in obj) acc[key] = obj[key];
    return acc;
  }, {});
}

export function omit(obj, keys) {
  return Object.fromEntries(
    Object.entries(obj).filter(([k]) => !keys.includes(k))
  );
}

export function slugify(str) {
  return str
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2);
}
`;
  await fs.writeFile(path.join(utilsPath, `helpers.${e}`), content);
}

async function writeEnvFile(projectPath, database) {
  let content = `# Nexorix Environment Configuration
NODE_ENV=development
PORT=3000

# JWT
JWT_SECRET=change-this-secret-in-production
JWT_EXPIRES_IN=7d
`;

  if (database === 'mysql') {
    content += `
# MySQL
DB_HOST=localhost
DB_PORT=3306
DB_USER=root
DB_PASSWORD=
DB_NAME=nexorix_db
`;
  }

  if (database === 'sqlite') {
    content += `
# SQLite
DB_PATH=./data/database.sqlite
`;
  }

  await fs.writeFile(path.join(projectPath, '.env'), content);
  await fs.writeFile(path.join(projectPath, '.env.example'), content);
}

async function writeReadme(projectPath, name, database, auth, cache, type, typescript = false) {
  const content = `# ${name}

> Generated by [Nexorix](https://github.com/Nexorix-Group/nexorix) — Structure, optimize and scale your backend.

## Stack

- Node.js ${typescript ? '+ TypeScript' : '(ESM)'}
- HTTP native server
${database === 'mysql' ? '- MySQL (mysql2)' : ''}
${database === 'sqlite' ? '- SQLite (better-sqlite3)' : ''}
${auth ? '- JWT Authentication' : ''}
${cache ? '- In-memory Cache' : ''}

## Getting Started

\`\`\`bash
npm install
cp .env.example .env
${typescript ? 'npm run dev' : 'npm start'}
\`\`\`

${typescript ? `## Build

\`\`\`bash
npm run build        # Compile TypeScript → dist/
npm start            # Run compiled output
npm run build:check  # Type-check without emitting
\`\`\`

` : ''}## Project Structure

\`\`\`
src/
├── app/
│   ├── server.${typescript ? 'ts' : 'js'}       # HTTP server factory
│   └── routes.${typescript ? 'ts' : 'js'}       # Route definitions
├── modules/
│   └── example/        # Example module (controller + service + repository)
├── core/
│   ├── middleware/     # Auth, error handling
│   ├── database/       # DB connection layer
│   └── utils/          # Helpers
├── config/
│   └── env.${typescript ? 'ts' : 'js'}          # Environment config
└── main.${typescript ? 'ts' : 'js'}             # Entry point
\`\`\`

## API Endpoints

| Method | Path | Description |
|--------|------|-------------|
| GET | / | Health check |
| GET | /health | Server health |
| GET | /api/examples | List examples |
| GET | /api/examples/:id | Get example by ID |
| POST | /api/examples | Create example |

## Nexorix Commands

\`\`\`bash
nexorix generate module <name>   # Generate a new module
nexorix add <plugin>             # Add a plugin
nexorix analyze                  # Analyze code quality
nexorix doctor                   # Check project health
\`\`\`

## Type: ${type === 'microservice' ? 'Microservice' : 'API REST'}
`;
  await fs.writeFile(path.join(projectPath, 'README.md'), content);
}

async function writeGitignore(projectPath, typescript = false) {
  const content = `node_modules/
.env
*.log
dist/
data/
.DS_Store
${typescript ? 'dist/' : ''}
`;
  await fs.writeFile(path.join(projectPath, '.gitignore'), content);
}

async function writeDockerFiles(projectPath, name, database, typescript = false) {
  const port = 3000;
  const nodeImage = 'node:20-alpine';
  const mainEntry = typescript ? 'dist/main.js' : 'src/main.js';
  const buildStep = typescript
    ? `\n# Build TypeScript\nRUN npm run build\n`
    : '';
  const devDepsStep = typescript
    ? `\n# Install all deps (including devDeps for build)\nRUN npm ci\n${buildStep}`
    : `\n# Install production deps only\nRUN npm ci --omit=dev\n`;

  // Dockerfile
  const dockerfile = `# Generated by Nexorix — https://github.com/Nexorix-Group/nexorix
FROM ${nodeImage} AS base
WORKDIR /app

# Install dependencies
COPY package*.json ./
${devDepsStep}
# Copy source
COPY . .
${typescript ? `
# Production stage
FROM ${nodeImage} AS production
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=base /app/dist ./dist
` : ''}
# Expose port
EXPOSE ${port}

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD wget -qO- http://localhost:${port}/health || exit 1

# Start
CMD ["node", "${mainEntry}"]
`;

  // .dockerignore
  const dockerignore = `node_modules
.env
*.log
.git
.gitignore
dist
coverage
README.md
`;

  // docker-compose.yml base
  let composeServices = `  app:
    build: .
    container_name: ${name}-app
    restart: unless-stopped
    ports:
      - "\${PORT:-${port}}:${port}"
    environment:
      - NODE_ENV=\${NODE_ENV:-production}
      - PORT=${port}
      - JWT_SECRET=\${JWT_SECRET}
    depends_on:${database === 'mysql' ? '\n      - db' : ' []'}
    networks:
      - ${name}-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${port}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
`;

  if (database === 'mysql') {
    composeServices += `
  db:
    image: mysql:8.0
    container_name: ${name}-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: \${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: \${DB_NAME:-nexorix_db}
      MYSQL_USER: \${DB_USER:-nexorix}
      MYSQL_PASSWORD: \${DB_PASSWORD:-nexorixpass}
    ports:
      - "\${DB_PORT:-3306}:3306"
    volumes:
      - ${name}-db-data:/var/lib/mysql
    networks:
      - ${name}-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
`;
  }

  const composeVolumes = database === 'mysql'
    ? `\nvolumes:\n  ${name}-db-data:\n`
    : '';

  const dockerCompose = `# Generated by Nexorix — https://github.com/Nexorix-Group/nexorix
services:
${composeServices}
networks:
  ${name}-network:
    driver: bridge
${composeVolumes}`;

  // .env additions for docker
  const envDockerAdditions = database === 'mysql'
    ? `\n# Docker / MySQL\nDB_ROOT_PASSWORD=rootpassword\nDB_USER=nexorix\nDB_PASSWORD=nexorixpass\nDB_NAME=nexorix_db\nDB_HOST=db\nDB_PORT=3306\n`
    : '';

  await fs.writeFile(path.join(projectPath, 'Dockerfile'), dockerfile);
  await fs.writeFile(path.join(projectPath, '.dockerignore'), dockerignore);
  await fs.writeFile(path.join(projectPath, 'docker-compose.yml'), dockerCompose);

  // Append docker env vars to .env
  if (envDockerAdditions) {
    await fs.appendFile(path.join(projectPath, '.env'), envDockerAdditions);
    await fs.appendFile(path.join(projectPath, '.env.example'), envDockerAdditions);
  }
}

async function writeTsConfig(projectPath) {
  const tsconfig = {
    compilerOptions: {
      target: 'ES2022',
      module: 'CommonJS',
      moduleResolution: 'node',
      lib: ['ES2022'],
      outDir: './dist',
      rootDir: './src',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      declaration: true,
      declarationMap: true,
      sourceMap: true,
    },
    include: ['src/**/*'],
    exclude: ['node_modules', 'dist'],
  };

  await fs.writeJson(path.join(projectPath, 'tsconfig.json'), tsconfig, { spaces: 2 });
}

async function writeAuthPlugin(projectPath, typescript = false) {
  const e = ext(typescript);
  const pluginPath = path.join(projectPath, 'src', 'core', 'plugins', 'auth');
  await fs.ensureDir(pluginPath);

  const content = typescript
    ? `export interface JwtPayload {
  [key: string]: unknown;
  iat?: number;
  exp?: number;
}

export function generateToken(payload: JwtPayload, secret = 'nexorix-secret', expiresInSeconds = 604800): string {
  const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url');
  const body = Buffer.from(JSON.stringify({
    ...payload,
    iat: Math.floor(Date.now() / 1000),
    exp: Math.floor(Date.now() / 1000) + expiresInSeconds,
  })).toString('base64url');
  const signature = Buffer.from(\`\${header}.\${body}.\${secret}\`).toString('base64url');
  return \`\${header}.\${body}.\${signature}\`;
}

export function verifyToken(token: string): JwtPayload {
  try {
    const parts = token.split('.');
    if (parts.length !== 3) throw new Error('Invalid token format');
    const payload = JSON.parse(Buffer.from(parts[1], 'base64url').toString()) as JwtPayload;
    if (payload.exp && payload.exp < Math.floor(Date.now() / 1000)) throw new Error('Token expired');
    return payload;
  } catch (err) {
    throw new Error(\`Token invalid: \${(err as Error).message}\`);
  }
}
`
    : `import { config } from '../../../config/env.js';

export function generateToken(payload) {
  const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url');
  const body = Buffer.from(JSON.stringify({
    ...payload,
    iat: Math.floor(Date.now() / 1000),
    exp: Math.floor(Date.now() / 1000) + 7 * 24 * 60 * 60,
  })).toString('base64url');
  const signature = Buffer.from(\`\${header}.\${body}.\${config.jwt.secret}\`).toString('base64url');
  return \`\${header}.\${body}.\${signature}\`;
}

export function verifyToken(token) {
  try {
    const parts = token.split('.');
    if (parts.length !== 3) throw new Error('Invalid token format');
    const payload = JSON.parse(Buffer.from(parts[1], 'base64url').toString());
    if (payload.exp < Math.floor(Date.now() / 1000)) throw new Error('Token expired');
    return payload;
  } catch (err) {
    throw new Error(\`Token invalid: \${err.message}\`);
  }
}
`;
  await fs.writeFile(path.join(pluginPath, `index.${e}`), content);
}

async function writeMysqlPlugin(projectPath) {
  // Already handled in writeDatabaseLayer
}

async function writeSqlitePlugin(projectPath) {
  // Already handled in writeDatabaseLayer
}

async function writeCachePlugin(projectPath, typescript = false) {
  const e = ext(typescript);
  const pluginPath = path.join(projectPath, 'src', 'core', 'plugins', 'cache');
  await fs.ensureDir(pluginPath);

  const content = typescript
    ? `/**
 * Cache Plugin — In-memory cache with TTL support
 */

const store = new Map<string, unknown>();
const ttlStore = new Map<string, ReturnType<typeof setTimeout>>();

export const cache = {
  set(key: string, value: unknown, ttlSeconds = 300): void {
    store.set(key, value);
    if (ttlSeconds > 0) {
      const existing = ttlStore.get(key);
      if (existing) clearTimeout(existing);
      const timer = setTimeout(() => {
        store.delete(key);
        ttlStore.delete(key);
      }, ttlSeconds * 1000);
      ttlStore.set(key, timer);
    }
  },

  get<T = unknown>(key: string): T | null {
    return (store.get(key) as T) ?? null;
  },

  has(key: string): boolean {
    return store.has(key);
  },

  delete(key: string): void {
    const timer = ttlStore.get(key);
    if (timer) clearTimeout(timer);
    store.delete(key);
    ttlStore.delete(key);
  },

  clear(): void {
    for (const timer of ttlStore.values()) clearTimeout(timer);
    store.clear();
    ttlStore.clear();
  },

  size(): number {
    return store.size;
  },

  async getOrSet<T>(key: string, fn: () => Promise<T>, ttlSeconds = 300): Promise<T> {
    if (this.has(key)) return this.get<T>(key) as T;
    const value = await fn();
    this.set(key, value, ttlSeconds);
    return value;
  },
};
`
    : `/**
 * Cache Plugin — In-memory cache layer
 */

const store = new Map();
const ttlStore = new Map();

export const cache = {
  set(key, value, ttlSeconds = 300) {
    store.set(key, value);
    if (ttlSeconds > 0) {
      const existing = ttlStore.get(key);
      if (existing) clearTimeout(existing);
      const timer = setTimeout(() => {
        store.delete(key);
        ttlStore.delete(key);
      }, ttlSeconds * 1000);
      ttlStore.set(key, timer);
    }
  },

  get(key) { return store.get(key) ?? null; },
  has(key) { return store.has(key); },

  delete(key) {
    const timer = ttlStore.get(key);
    if (timer) clearTimeout(timer);
    store.delete(key);
    ttlStore.delete(key);
  },

  clear() {
    for (const timer of ttlStore.values()) clearTimeout(timer);
    store.clear();
    ttlStore.clear();
  },

  size() { return store.size; },

  async getOrSet(key, fn, ttlSeconds = 300) {
    if (this.has(key)) return this.get(key);
    const value = await fn();
    this.set(key, value, ttlSeconds);
    return value;
  },
};
`;
  await fs.writeFile(path.join(pluginPath, `index.${e}`), content);
}

async function writeLoggerPlugin(projectPath, typescript = false) {
  const e = ext(typescript);
  const pluginPath = path.join(projectPath, 'src', 'core', 'plugins', 'logger');
  await fs.ensureDir(pluginPath);

  const content = typescript
    ? `/**
 * Logger Plugin — Structured logging (replaces console.log)
 */

type LogLevel = 'debug' | 'info' | 'warn' | 'error';
type LogMeta = Record<string, unknown>;

const LEVELS: Record<LogLevel, number> = { debug: 0, info: 1, warn: 2, error: 3 };
const ENV_LEVEL = process.env.LOG_LEVEL?.toLowerCase() as LogLevel | undefined;
const currentLevel = LEVELS[ENV_LEVEL ?? 'info'] ?? LEVELS.info;

const COLORS: Record<string, string> = {
  debug: '\\x1b[36m',
  info:  '\\x1b[32m',
  warn:  '\\x1b[33m',
  error: '\\x1b[31m',
  reset: '\\x1b[0m',
};

function format(level: LogLevel, message: string, meta: LogMeta = {}): string {
  const ts = new Date().toISOString();
  const hasMeta = Object.keys(meta).length > 0;
  if (process.env.LOG_FORMAT === 'json') {
    return JSON.stringify({ timestamp: ts, level, message, ...(hasMeta ? { meta } : {}) });
  }
  const color = COLORS[level] || '';
  const metaStr = hasMeta ? \` \${JSON.stringify(meta)}\` : '';
  return \`\${color}[\${level.toUpperCase()}]\${COLORS.reset} \${ts} — \${message}\${metaStr}\`;
}

export const logger = {
  debug(message: string, meta: LogMeta = {}): void {
    if (currentLevel <= LEVELS.debug) process.stdout.write(format('debug', message, meta) + '\\n');
  },
  info(message: string, meta: LogMeta = {}): void {
    if (currentLevel <= LEVELS.info) process.stdout.write(format('info', message, meta) + '\\n');
  },
  warn(message: string, meta: LogMeta = {}): void {
    if (currentLevel <= LEVELS.warn) process.stderr.write(format('warn', message, meta) + '\\n');
  },
  error(message: string, meta: LogMeta = {}): void {
    if (currentLevel <= LEVELS.error) process.stderr.write(format('error', message, meta) + '\\n');
  },
};
`
    : `/**
 * Logger Plugin — Structured logging (replaces console.log)
 */

const LEVELS = { debug: 0, info: 1, warn: 2, error: 3 };
const currentLevel = LEVELS[process.env.LOG_LEVEL] ?? LEVELS.info;

const COLORS = {
  debug: '\\x1b[36m',
  info:  '\\x1b[32m',
  warn:  '\\x1b[33m',
  error: '\\x1b[31m',
  reset: '\\x1b[0m',
};

function format(level, message, meta = {}) {
  const ts = new Date().toISOString();
  const hasMeta = Object.keys(meta).length > 0;
  if (process.env.LOG_FORMAT === 'json') {
    return JSON.stringify({ timestamp: ts, level, message, ...(hasMeta ? { meta } : {}) });
  }
  const color = COLORS[level] || '';
  const metaStr = hasMeta ? \` \${JSON.stringify(meta)}\` : '';
  return \`\${color}[\${level.toUpperCase()}]\${COLORS.reset} \${ts} — \${message}\${metaStr}\`;
}

export const logger = {
  debug(message, meta = {}) {
    if (currentLevel <= LEVELS.debug) process.stdout.write(format('debug', message, meta) + '\\n');
  },
  info(message, meta = {}) {
    if (currentLevel <= LEVELS.info) process.stdout.write(format('info', message, meta) + '\\n');
  },
  warn(message, meta = {}) {
    if (currentLevel <= LEVELS.warn) process.stderr.write(format('warn', message, meta) + '\\n');
  },
  error(message, meta = {}) {
    if (currentLevel <= LEVELS.error) process.stderr.write(format('error', message, meta) + '\\n');
  },
};
`;
  await fs.writeFile(path.join(pluginPath, `index.${e}`), content);
}
