import chalk from 'chalk';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export async function createProject(config) {
  const { name, database, auth, cache, type, optimizations } = config;
  const projectPath = path.join(process.cwd(), name);

  // Check if directory already exists
  if (await fs.pathExists(projectPath)) {
    console.log(chalk.red(`  ✖ Directory "${name}" already exists.`));
    console.log('');
    process.exit(1);
  }

  console.log(chalk.gray(`  Creating project: ${chalk.white(name)}...`));

  // Create directory structure
  const dirs = [
    'src/app',
    'src/modules/example',
    'src/core/middleware',
    'src/core/database',
    'src/core/utils',
    'src/config',
  ];

  for (const dir of dirs) {
    await fs.ensureDir(path.join(projectPath, dir));
  }

  // Generate files
  await writePackageJson(projectPath, name, database, auth, cache);
  await writeMainJs(projectPath, type);
  await writeServerJs(projectPath);
  await writeRoutesJs(projectPath, auth);
  await writeEnvConfig(projectPath, database);
  await writeExampleModule(projectPath);
  await writeMiddleware(projectPath, auth);
  await writeDatabaseLayer(projectPath, database);
  await writeUtils(projectPath);
  await writeEnvFile(projectPath, database);
  await writeReadme(projectPath, name, database, auth, cache, type);
  await writeGitignore(projectPath);

  // Optional plugins
  if (auth) await writeAuthPlugin(projectPath);
  if (database === 'mysql') await writeMysqlPlugin(projectPath);
  if (database === 'sqlite') await writeSqlitePlugin(projectPath);
  if (cache) await writeCachePlugin(projectPath);
  if (optimizations) await writeLoggerPlugin(projectPath);

  console.log(chalk.green(`  ✔ Project created: ${chalk.bold(name)}`));
  console.log('');
  console.log(chalk.gray('  Next steps:'));
  console.log(chalk.cyan(`    cd ${name}`));
  console.log(chalk.cyan('    npm install'));
  console.log(chalk.cyan('    nexorix run'));
  console.log('');
}

async function writePackageJson(projectPath, name, database, auth, cache) {
  const deps = {
    'dotenv': '^16.4.5',
  };

  if (database === 'mysql') deps['mysql2'] = '^3.9.7';
  if (database === 'sqlite') deps['better-sqlite3'] = '^9.4.3';
  if (auth) deps['jsonwebtoken'] = '^9.0.2';
  if (cache) deps['node-cache'] = '^5.1.2';

  const pkg = {
    name,
    version: '1.0.0',
    description: `${name} — generated by Nexorix`,
    type: 'module',
    scripts: {
      start: 'node src/main.js',
      dev: 'node --watch src/main.js',
    },
    dependencies: deps,
  };

  await fs.writeJson(path.join(projectPath, 'package.json'), pkg, { spaces: 2 });
}

async function writeMainJs(projectPath, type) {
  const content = `import { createServer } from './app/server.js';
import { config } from './config/env.js';

const PORT = config.port || 3000;

const server = createServer();

server.listen(PORT, () => {
  console.log(\`[nexorix] Server running on http://localhost:\${PORT}\`);
  console.log(\`[nexorix] Environment: \${config.env}\`);
  ${type === 'microservice' ? "console.log('[nexorix] Mode: Microservice');" : "console.log('[nexorix] Mode: API REST');"}
});

server.on('error', (err) => {
  console.error('[nexorix] Server error:', err.message);
  process.exit(1);
});
`;
  await fs.writeFile(path.join(projectPath, 'src', 'main.js'), content);
}

async function writeServerJs(projectPath) {
  const content = `import http from 'http';
import { router } from './routes.js';

export function createServer() {
  return http.createServer((req, res) => {
    // CORS headers
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

    if (req.method === 'OPTIONS') {
      res.writeHead(204);
      res.end();
      return;
    }

    // Body parser
    let body = '';
    req.on('data', (chunk) => { body += chunk.toString(); });
    req.on('end', () => {
      try {
        req.body = body ? JSON.parse(body) : {};
      } catch {
        req.body = {};
      }
      router(req, res);
    });
  });
}

export function sendJson(res, statusCode, data) {
  res.writeHead(statusCode, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(data));
}
`;
  await fs.writeFile(path.join(projectPath, 'src', 'app', 'server.js'), content);
}

async function writeRoutesJs(projectPath, auth) {
  const content = `import { sendJson } from './server.js';
import { exampleController } from '../modules/example/example.controller.js';
${auth ? "import { authMiddleware } from '../core/middleware/auth.middleware.js';" : ''}

const routes = {
  'GET /': (req, res) => sendJson(res, 200, {
    status: 'ok',
    message: 'Nexorix API is running',
    version: '1.0.0',
  }),
  'GET /health': (req, res) => sendJson(res, 200, {
    status: 'healthy',
    uptime: process.uptime(),
    timestamp: new Date().toISOString(),
  }),
  'GET /api/examples': exampleController.list,
  'GET /api/examples/:id': exampleController.findById,
  'POST /api/examples': exampleController.create,
};

export function router(req, res) {
  const url = req.url.split('?')[0];
  const method = req.method;

  // Match dynamic routes (e.g. /api/examples/:id)
  for (const [pattern, handler] of Object.entries(routes)) {
    const [routeMethod, routePath] = pattern.split(' ');
    if (routeMethod !== method) continue;

    const match = matchRoute(routePath, url);
    if (match) {
      req.params = match;
      ${auth ? `
      // Protected routes
      const protectedPaths = ['/api/examples'];
      const isProtected = protectedPaths.some(p => url.startsWith(p));
      if (isProtected && method !== 'GET') {
        const authResult = authMiddleware(req, res);
        if (!authResult) return;
      }
      ` : ''}
      return handler(req, res);
    }
  }

  sendJson(res, 404, { error: 'Route not found', path: url, method });
}

function matchRoute(pattern, url) {
  const patternParts = pattern.split('/');
  const urlParts = url.split('/');

  if (patternParts.length !== urlParts.length) return null;

  const params = {};
  for (let i = 0; i < patternParts.length; i++) {
    if (patternParts[i].startsWith(':')) {
      params[patternParts[i].slice(1)] = urlParts[i];
    } else if (patternParts[i] !== urlParts[i]) {
      return null;
    }
  }
  return params;
}
`;
  await fs.writeFile(path.join(projectPath, 'src', 'app', 'routes.js'), content);
}

async function writeEnvConfig(projectPath, database) {
  const content = `import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

function loadEnv() {
  const envPath = join(process.cwd(), '.env');
  if (existsSync(envPath)) {
    const lines = readFileSync(envPath, 'utf-8').split('\\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const [key, ...rest] = trimmed.split('=');
      if (key && !process.env[key]) {
        process.env[key] = rest.join('=').trim();
      }
    }
  }
}

loadEnv();

export const config = {
  env: process.env.NODE_ENV || 'development',
  port: parseInt(process.env.PORT || '3000', 10),
  ${database === 'mysql' ? `
  db: {
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '3306', 10),
    user: process.env.DB_USER || 'root',
    password: process.env.DB_PASSWORD || '',
    database: process.env.DB_NAME || 'nexorix_db',
  },` : ''}
  ${database === 'sqlite' ? `
  db: {
    path: process.env.DB_PATH || './data/database.sqlite',
  },` : ''}
  jwt: {
    secret: process.env.JWT_SECRET || 'nexorix-secret-change-in-production',
    expiresIn: process.env.JWT_EXPIRES_IN || '7d',
  },
};
`;
  await fs.writeFile(path.join(projectPath, 'src', 'config', 'env.js'), content);
}

async function writeExampleModule(projectPath) {
  const modulePath = path.join(projectPath, 'src', 'modules', 'example');

  // Controller
  const controller = `import { sendJson } from '../../app/server.js';
import { ExampleService } from './example.service.js';

const service = new ExampleService();

export const exampleController = {
  async list(req, res) {
    try {
      const data = await service.findAll();
      sendJson(res, 200, { data, total: data.length });
    } catch (err) {
      sendJson(res, 500, { error: err.message });
    }
  },

  async findById(req, res) {
    try {
      const item = await service.findById(req.params.id);
      if (!item) return sendJson(res, 404, { error: 'Not found' });
      sendJson(res, 200, { data: item });
    } catch (err) {
      sendJson(res, 500, { error: err.message });
    }
  },

  async create(req, res) {
    try {
      const item = await service.create(req.body);
      sendJson(res, 201, { data: item, message: 'Created successfully' });
    } catch (err) {
      sendJson(res, 400, { error: err.message });
    }
  },
};
`;

  // Service
  const service = `import { ExampleRepository } from './example.repository.js';

export class ExampleService {
  constructor() {
    this.repository = new ExampleRepository();
  }

  async findAll() {
    return this.repository.findAll();
  }

  async findById(id) {
    if (!id) throw new Error('ID is required');
    return this.repository.findById(id);
  }

  async create(data) {
    if (!data || Object.keys(data).length === 0) {
      throw new Error('Data is required');
    }
    return this.repository.create(data);
  }
}
`;

  // Repository
  const repository = `// In-memory repository — replace with real DB layer
const store = [
  { id: '1', name: 'Example Item 1', createdAt: new Date().toISOString() },
  { id: '2', name: 'Example Item 2', createdAt: new Date().toISOString() },
];

let nextId = 3;

export class ExampleRepository {
  async findAll() {
    return [...store];
  }

  async findById(id) {
    return store.find((item) => item.id === String(id)) || null;
  }

  async create(data) {
    const item = {
      id: String(nextId++),
      ...data,
      createdAt: new Date().toISOString(),
    };
    store.push(item);
    return item;
  }
}
`;

  await fs.writeFile(path.join(modulePath, 'example.controller.js'), controller);
  await fs.writeFile(path.join(modulePath, 'example.service.js'), service);
  await fs.writeFile(path.join(modulePath, 'example.repository.js'), repository);
}

async function writeMiddleware(projectPath, auth) {
  const middlewarePath = path.join(projectPath, 'src', 'core', 'middleware');

  const authMiddleware = `import { config } from '../../config/env.js';

// Simple JWT verification without external dependency
// For production, install jsonwebtoken: npm install jsonwebtoken
export function authMiddleware(req, res) {
  const authHeader = req.headers['authorization'];

  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    res.writeHead(401, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Unauthorized — missing token' }));
    return false;
  }

  const token = authHeader.split(' ')[1];

  try {
    // Basic token validation (replace with jwt.verify in production)
    if (!token || token.length < 10) {
      throw new Error('Invalid token');
    }
    // Decode payload (base64 middle part)
    const parts = token.split('.');
    if (parts.length === 3) {
      const payload = JSON.parse(Buffer.from(parts[1], 'base64url').toString());
      if (payload.exp && payload.exp < Math.floor(Date.now() / 1000)) {
        throw new Error('Token expired');
      }
      req.user = payload;
    }
    return true;
  } catch (err) {
    res.writeHead(401, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: \`Unauthorized — \${err.message}\` }));
    return false;
  }
}
`;

  const errorMiddleware = `export function errorHandler(err, req, res) {
  const statusCode = err.statusCode || 500;
  const message = err.message || 'Internal Server Error';

  console.error(\`[error] \${req.method} \${req.url} — \${message}\`);

  res.writeHead(statusCode, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({
    error: message,
    path: req.url,
    timestamp: new Date().toISOString(),
  }));
}
`;

  await fs.writeFile(path.join(middlewarePath, 'auth.middleware.js'), authMiddleware);
  await fs.writeFile(path.join(middlewarePath, 'error.middleware.js'), errorMiddleware);
}

async function writeDatabaseLayer(projectPath, database) {
  const dbPath = path.join(projectPath, 'src', 'core', 'database');

  if (database === 'mysql') {
    const content = `import { config } from '../../config/env.js';
// Requires: npm install mysql2
import mysql from 'mysql2/promise';

let pool = null;

export async function getPool() {
  if (!pool) {
    pool = mysql.createPool({
      host: config.db.host,
      port: config.db.port,
      user: config.db.user,
      password: config.db.password,
      database: config.db.database,
      waitForConnections: true,
      connectionLimit: 10,
      queueLimit: 0,
    });
    console.log('[database] MySQL pool created');
  }
  return pool;
}

export async function query(sql, params = []) {
  const pool = await getPool();
  const [rows] = await pool.execute(sql, params);
  return rows;
}
`;
    await fs.writeFile(path.join(dbPath, 'connection.js'), content);
  } else if (database === 'sqlite') {
    const content = `import { config } from '../../config/env.js';
import { existsSync, mkdirSync } from 'fs';
import { dirname } from 'path';
// Requires: npm install better-sqlite3
import Database from 'better-sqlite3';

let db = null;

export function getDb() {
  if (!db) {
    const dir = dirname(config.db.path);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    db = new Database(config.db.path);
    db.pragma('journal_mode = WAL');
    console.log('[database] SQLite connected:', config.db.path);
  }
  return db;
}

export function query(sql, params = []) {
  const db = getDb();
  return db.prepare(sql).all(params);
}
`;
    await fs.writeFile(path.join(dbPath, 'connection.js'), content);
  } else {
    const content = `// No database configured.
// Run: nexorix add mysql  or  nexorix add sqlite
// to add a database layer.

export function getDb() {
  throw new Error('No database configured. Run: nexorix add mysql');
}
`;
    await fs.writeFile(path.join(dbPath, 'connection.js'), content);
  }
}

async function writeUtils(projectPath) {
  const utilsPath = path.join(projectPath, 'src', 'core', 'utils');

  const content = `/**
 * Nexorix Core Utilities
 */

export function paginate(array, page = 1, limit = 10) {
  const offset = (page - 1) * limit;
  return {
    data: array.slice(offset, offset + limit),
    pagination: {
      page,
      limit,
      total: array.length,
      pages: Math.ceil(array.length / limit),
    },
  };
}

export function pick(obj, keys) {
  return keys.reduce((acc, key) => {
    if (key in obj) acc[key] = obj[key];
    return acc;
  }, {});
}

export function omit(obj, keys) {
  return Object.fromEntries(
    Object.entries(obj).filter(([k]) => !keys.includes(k))
  );
}

export function slugify(str) {
  return str
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2);
}
`;
  await fs.writeFile(path.join(utilsPath, 'helpers.js'), content);
}

async function writeEnvFile(projectPath, database) {
  let content = `# Nexorix Environment Configuration
NODE_ENV=development
PORT=3000

# JWT
JWT_SECRET=change-this-secret-in-production
JWT_EXPIRES_IN=7d
`;

  if (database === 'mysql') {
    content += `
# MySQL
DB_HOST=localhost
DB_PORT=3306
DB_USER=root
DB_PASSWORD=
DB_NAME=nexorix_db
`;
  }

  if (database === 'sqlite') {
    content += `
# SQLite
DB_PATH=./data/database.sqlite
`;
  }

  await fs.writeFile(path.join(projectPath, '.env'), content);
  await fs.writeFile(path.join(projectPath, '.env.example'), content);
}

async function writeReadme(projectPath, name, database, auth, cache, type) {
  const content = `# ${name}

> Generated by [Nexorix](https://github.com/nexorix/nexorix) — Structure, optimize and scale your backend.

## Stack

- Node.js (ESM)
- HTTP native server
${database === 'mysql' ? '- MySQL (mysql2)' : ''}
${database === 'sqlite' ? '- SQLite (better-sqlite3)' : ''}
${auth ? '- JWT Authentication' : ''}
${cache ? '- In-memory Cache' : ''}

## Getting Started

\`\`\`bash
npm install
cp .env.example .env
npm start
\`\`\`

## Project Structure

\`\`\`
src/
├── app/
│   ├── server.js       # HTTP server factory
│   └── routes.js       # Route definitions
├── modules/
│   └── example/        # Example module (controller + service + repository)
├── core/
│   ├── middleware/     # Auth, error handling
│   ├── database/       # DB connection layer
│   └── utils/          # Helpers
├── config/
│   └── env.js          # Environment config
└── main.js             # Entry point
\`\`\`

## API Endpoints

| Method | Path | Description |
|--------|------|-------------|
| GET | / | Health check |
| GET | /health | Server health |
| GET | /api/examples | List examples |
| GET | /api/examples/:id | Get example by ID |
| POST | /api/examples | Create example |

## Nexorix Commands

\`\`\`bash
nexorix generate module <name>   # Generate a new module
nexorix add <plugin>             # Add a plugin
nexorix analyze                  # Analyze code quality
nexorix doctor                   # Check project health
\`\`\`

## Type: ${type === 'microservice' ? 'Microservice' : 'API REST'}
`;
  await fs.writeFile(path.join(projectPath, 'README.md'), content);
}

async function writeGitignore(projectPath) {
  const content = `node_modules/
.env
*.log
dist/
data/
.DS_Store
`;
  await fs.writeFile(path.join(projectPath, '.gitignore'), content);
}

async function writeAuthPlugin(projectPath) {
  const pluginPath = path.join(projectPath, 'src', 'core', 'plugins', 'auth');
  await fs.ensureDir(pluginPath);

  const content = `import { config } from '../../../config/env.js';

/**
 * Auth Plugin — JWT token generation and validation
 * For production: npm install jsonwebtoken
 */

export function generateToken(payload) {
  // Simple base64 token (replace with jwt.sign in production)
  const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url');
  const body = Buffer.from(JSON.stringify({
    ...payload,
    iat: Math.floor(Date.now() / 1000),
    exp: Math.floor(Date.now() / 1000) + 7 * 24 * 60 * 60, // 7 days
  })).toString('base64url');
  const signature = Buffer.from(\`\${header}.\${body}.\${config.jwt.secret}\`).toString('base64url');
  return \`\${header}.\${body}.\${signature}\`;
}

export function verifyToken(token) {
  try {
    const parts = token.split('.');
    if (parts.length !== 3) throw new Error('Invalid token format');
    const payload = JSON.parse(Buffer.from(parts[1], 'base64url').toString());
    if (payload.exp < Math.floor(Date.now() / 1000)) throw new Error('Token expired');
    return payload;
  } catch (err) {
    throw new Error(\`Token invalid: \${err.message}\`);
  }
}
`;
  await fs.writeFile(path.join(pluginPath, 'index.js'), content);
}

async function writeMysqlPlugin(projectPath) {
  // Already handled in writeDatabaseLayer
}

async function writeSqlitePlugin(projectPath) {
  // Already handled in writeDatabaseLayer
}

async function writeCachePlugin(projectPath) {
  const pluginPath = path.join(projectPath, 'src', 'core', 'plugins', 'cache');
  await fs.ensureDir(pluginPath);

  const content = `/**
 * Cache Plugin — In-memory cache layer
 */

const store = new Map();
const ttlStore = new Map();

export const cache = {
  set(key, value, ttlSeconds = 300) {
    store.set(key, value);
    if (ttlSeconds > 0) {
      const existing = ttlStore.get(key);
      if (existing) clearTimeout(existing);
      const timer = setTimeout(() => {
        store.delete(key);
        ttlStore.delete(key);
      }, ttlSeconds * 1000);
      ttlStore.set(key, timer);
    }
  },

  get(key) {
    return store.get(key) ?? null;
  },

  has(key) {
    return store.has(key);
  },

  delete(key) {
    const timer = ttlStore.get(key);
    if (timer) clearTimeout(timer);
    store.delete(key);
    ttlStore.delete(key);
  },

  clear() {
    for (const timer of ttlStore.values()) clearTimeout(timer);
    store.clear();
    ttlStore.clear();
  },

  size() {
    return store.size;
  },

  stats() {
    return { size: store.size, keys: [...store.keys()] };
  },
};
`;
  await fs.writeFile(path.join(pluginPath, 'index.js'), content);
}

async function writeLoggerPlugin(projectPath) {
  const pluginPath = path.join(projectPath, 'src', 'core', 'plugins', 'logger');
  await fs.ensureDir(pluginPath);

  const content = `/**
 * Logger Plugin — Structured logging (replaces console.log)
 */

const LEVELS = { debug: 0, info: 1, warn: 2, error: 3 };
const currentLevel = LEVELS[process.env.LOG_LEVEL] ?? LEVELS.info;

function format(level, message, meta = {}) {
  const ts = new Date().toISOString();
  const hasMeta = Object.keys(meta).length > 0;
  return JSON.stringify({
    timestamp: ts,
    level,
    message,
    ...(hasMeta ? { meta } : {}),
  });
}

export const logger = {
  debug(message, meta = {}) {
    if (currentLevel <= LEVELS.debug) {
      process.stdout.write(format('debug', message, meta) + '\\n');
    }
  },

  info(message, meta = {}) {
    if (currentLevel <= LEVELS.info) {
      process.stdout.write(format('info', message, meta) + '\\n');
    }
  },

  warn(message, meta = {}) {
    if (currentLevel <= LEVELS.warn) {
      process.stderr.write(format('warn', message, meta) + '\\n');
    }
  },

  error(message, meta = {}) {
    if (currentLevel <= LEVELS.error) {
      process.stderr.write(format('error', message, meta) + '\\n');
    }
  },
};
`;
  await fs.writeFile(path.join(pluginPath, 'index.js'), content);
}
